version: "3"

services:
  mongodb:
    image: mongo
    restart: always
    networks:
      - task-network
    volumes:
      - mongodb-data:/data/db

  spring-app:
    image: sbk2k1/taskapp-spring-app:4.0.0
    depends_on:
      - mongodb
    expose:
      - 8080
    networks:
      - task-network
    volumes:
      - ./server/config/mongodb-url.txt:/app/config/mongodb-url.txt:ro
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/tasks-manager-api
      - SPRING_SECURIY_USERNAME=admin
      - SPRING_SECURIY_PASSWORD=admin

  react-app:
    image: sbk2k1/taskapp-react-app:4.0.0
    depends_on:
      - spring-app
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - task-network
    volumes:
      - ./client/src/config.json:/app/src/config.json:ro

networks:
  task-network:
    driver: bridge

volumes:
  mongodb-data:
